# Generated by Django 5.1.10 on 2025-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='analytical_report',
            field=models.ImageField(blank=True, help_text='Upload analytical report for the product', null=True, upload_to='products/analytical_reports/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/None/'),
        ),
    ]
