# Generated by Django 5.1.10 on 2025-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image_alter_product_analytical_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
