# Generated by Django 5.1.10 on 2025-07-08 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttagassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='products.product'),
        ),
        migrations.AlterField(
            model_name='producttagassignment',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='products.producttag'),
        ),
    ]
