# Generated by Django 5.1.10 on 2025-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_collection_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
