# Generated by Django 5.1.10 on 2025-07-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_collection_show_on_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
