# Generated by Django 5.1.10 on 2025-07-08 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_image_alter_product_analytical_report_and_more'),
        ('reviews', '0002_externalreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('one_star_count', models.PositiveIntegerField(default=0)),
                ('two_star_count', models.PositiveIntegerField(default=0)),
                ('three_star_count', models.PositiveIntegerField(default=0)),
                ('four_star_count', models.PositiveIntegerField(default=0)),
                ('five_star_count', models.PositiveIntegerField(default=0)),
                ('verified_buyers', models.PositiveIntegerField(default=0)),
                ('verified_buyer_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'External Reviews Summary',
                'verbose_name_plural': 'External Reviews Summaries',
            },
        ),
        migrations.AddField(
            model_name='externalreview',
            name='is_imported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externalreview',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='external_reviews', to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='externalreview',
            name='source',
            field=models.CharField(default='external', help_text='Source platform', max_length=100),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='author',
            field=models.CharField(help_text='Review author name', max_length=200),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='body',
            field=models.TextField(help_text='Review content/body'),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='product_title',
            field=models.CharField(help_text='Product title from external source', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='product_url',
            field=models.CharField(blank=True, help_text='Product URL from external source', max_length=500),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='review_id',
            field=models.UUIDField(help_text='External review UUID', unique=True),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='timestamp',
            field=models.DateTimeField(help_text='Original review timestamp'),
        ),
        migrations.AlterField(
            model_name='externalreview',
            name='title',
            field=models.CharField(blank=True, help_text='Review title', max_length=500),
        ),
        migrations.AddIndex(
            model_name='externalreview',
            index=models.Index(fields=['product', 'rating'], name='reviews_ext_product_b51b29_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreview',
            index=models.Index(fields=['verified_buyer'], name='reviews_ext_verifie_b3539f_idx'),
        ),
        migrations.AddIndex(
            model_name='externalreview',
            index=models.Index(fields=['timestamp'], name='reviews_ext_timesta_3899e5_idx'),
        ),
        migrations.AddField(
            model_name='reviewssummary',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_summary', to='products.product'),
        ),
    ]
